name: Build (Windows)
on:
  push:
    branches:
      - main
    paths:
      - build.py
      - rsrc/
      - src/
  pull_request:
    branches:
      - main
    paths:
      - build.py
      - rsrc/
      - src/
permissions: read-all
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: ilammy/msvc-dev-cmd@v1
    - name: 'Build "lll${{matrix.args}}"'
      run: python build.py${{matrix.args}}
      shell: cmd
    strategy:
      matrix:
        args:
          - ''
          - ' --release'
          - ' --standalone'
          - ' --standalone --release'
    timeout-minutes: 5
